---
- name: Download RKE2 installation script
  ansible.builtin.get_url:
    url: "{{ rke2_install_bash_url }}"
    dest: "{{ rke2_install_script_dir }}/rke2.sh"
    mode: 0700
    timeout: "{{ rke2_artifact_fetch_timeout }}"
  when: not rke2_airgap_mode

- name: Copy local RKE2 installation script
  ansible.builtin.copy:
    src: "{{ rke2_airgap_copy_sourcepath }}/rke2.sh"
    dest: "{{ rke2_install_script_dir }}/rke2.sh"
    mode: 0700
    force: yes
  when: rke2_airgap_mode

- name: Create RKE2 artifacts folder
  ansible.builtin.file:
    path: "{{ rke2_artifact_path }}"
    state: directory
    mode: 0700
  when: rke2_airgap_mode

- name: Copy local RKE2 artifacts
  ansible.builtin.copy:
    src: "{{ rke2_airgap_copy_sourcepath }}/{{ item }}"
    dest: "{{ rke2_artifact_path }}/{{ item }}"
    mode: 0640
    force: yes
  with_items: "{{ rke2_artifact }}"
  when: rke2_airgap_mode

- name: Airgap mode - additional images tarballs
  when:
    - rke2_airgap_mode
    - ( rke2_airgap_copy_additional_tarballs | length > 0 )
  block:
    - name: Create additional images tarballs folder
      ansible.builtin.file:
        path: "{{ rke2_tarball_images_path }}"
        state: directory
        mode: 0700
    - name: Copy additional tarball images RKE2 components
      ansible.builtin.copy:
        src: "{{ rke2_airgap_copy_sourcepath }}/{{ item }}"
        dest: "{{ rke2_tarball_images_path }}/{{ item }}"
        mode: 0644
        force: yes
      with_items: "{{ rke2_airgap_copy_additional_tarballs }}"

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Get stats of the FS object
  ansible.builtin.stat:
    path: /usr/local
  register: usr_local

- name: Check if separate partition
  ansible.builtin.command: grep '/usr/local ' /proc/mounts
  changed_when: false
  register: partition_result
  failed_when: partition_result.rc >= 2
  check_mode: false

- name: Set RKE2 bin path
  ansible.builtin.set_fact:
    rke2_bin_path: "{{ '/usr/local/bin/rke2' if (not usr_local.stat.writeable) or (partition_result.rc == 1) else '/opt/rke2/bin/rke2' }}"

- name: Check RKE2 version
  ansible.builtin.shell: |
    set -euo pipefail

    rke2_bin_path="{{ rke2_bin_path }}"
    rke2_service_name="{{ rke2_service_name }}"
    rke2_version="{{ rke2_version }}"

    if [ -f "$rke2_bin_path" ]; then
      installed_version="$($rke2_bin_path --version | awk '/rke2 version/ {print $3}')"
    else
      installed_version="not installed"
    fi

    if systemctl is-active --quiet $rke2_service_name && rke2_service_pid=$(systemctl show $rke2_service_name --property MainPID --value); then
      rke2_bin_path="$(realpath "/proc/$rke2_service_pid/exe")"
    fi

    # Linux appends the target of removed proc exe with ' (deleted)', making the path unavailable.
    if [ -f "$rke2_bin_path" ]; then
      running_version="$($rke2_bin_path --version | awk '/rke2 version/ {print $3}')"
    elif [ "$installed_version" = "not installed" ]; then
      running_version="$rke2_version"
    else
      running_version="outdated"
    fi

    echo "{\"installed_version\":\"$installed_version\",\"running_version\":\"$running_version\"}"
  args:
    executable: /bin/bash
  changed_when: false
  register: versions_check

- name: Set RKE2 versions
  when: not ansible_check_mode
  ansible.builtin.set_fact:
    installed_version: "{{ versions.installed_version }}"
    running_version: "{{ versions.running_version }}"
  vars:
    versions: "{{ versions_check.stdout | from_json }}"

- name: Prevent RKE2 downgrade
  when: not ansible_check_mode and installed_version != "not installed"
  ansible.builtin.assert:
    that:
      - rke2_version_clean is version(installed_version_clean, '>=')
    fail_msg: >
      Version downgrade is not allowed.
      Current installed version: {{ installed_version_clean }},
      desired version: {{ rke2_version_clean }}.
    success_msg: >
      Version check passed. Current installed version: {{ installed_version_clean }},
      desired version: {{ rke2_version_clean }}."
  vars:
    rke2_version_clean: "{{ rke2_version | regex_search('v([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') }}"
    installed_version_clean: "{{ installed_version | regex_search('v([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') }}"

- name: Run RKE2 install script
  when: not ansible_check_mode and rke2_version != installed_version
  block:
    - name: Run RKE2 install script with airgap variables
      ansible.builtin.command:
        cmd: "{{ rke2_install_script_dir }}/rke2.sh"
      environment:
        INSTALL_RKE2_ARTIFACT_PATH: "{{ rke2_artifact_path }}"
        INSTALL_RKE2_AGENT_IMAGES_DIR: "{{ rke2_data_path }}/agent/images"
        INSTALL_RKE2_METHOD: "{{ rke2_method }}"
      changed_when: false
      when: rke2_airgap_mode
    - name: Run RKE2 install script without airgap variables
      ansible.builtin.command:
        cmd: "{{ rke2_install_script_dir }}/rke2.sh"
      environment:
        INSTALL_RKE2_VERSION: "{{ rke2_version }}"
        INSTALL_RKE2_CHANNEL_URL: "{{ rke2_channel_url }}"
        INSTALL_RKE2_CHANNEL: "{{ rke2_channel }}"
        INSTALL_RKE2_METHOD: "{{ rke2_method }}"
      changed_when: false
      when: not rke2_airgap_mode

- name: Copy Custom Manifests
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/server/manifests/"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ rke2_custom_manifests }}"
  when: rke2_custom_manifests | length > 0

- name: Copy Static Pods
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/agent/pod-manifests/"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ rke2_static_pods }}"
  when: rke2_static_pods

- name: Copy RKE2 environment file
  ansible.builtin.template:
    src: rke2_environment.j2
    dest: "/etc/default/rke2-{{ rke2_type }}"
    owner: root
    group: root
    mode: 0644
  when:
    - rke2_environment_options is defined
    - rke2_environment_options|length > 0

- name: Conditional Image Imports
  when: rke2_conditional_image_imports is defined
  block:
    - name: Enable Conditional Image Imports
      ansible.builtin.copy:
        content: ""
        dest: "{{ rke2_tarball_images_path }}/.cache.json"
        mode: 0640
        force: false
      when: rke2_conditional_image_imports

    - name: Disable Conditional Image Imports
      ansible.builtin.file:
        path: "{{ rke2_tarball_images_path }}/.cache.json"
        state: absent
      when: not rke2_conditional_image_imports
